server:
  servlet:
    context-path: /
    tomcat:
      max-threads: 1000
      min-spare-threads: 30
      uri-encoding: utf-8
      remote_ip_header: x-forwarded-for
      protocol_header: x-forwarded-proto
      port-header: X-Forwarded-Port
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  session:
    timeout: 1800
  banner:
    location: config/banner.txt
  thymeleaf:
    mode: HTML
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true    
  profiles:
    active: dev
#  redis:
#    host: 127.0.0.1
  devtools:
    restart:
      enabled: false
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.personal.**.domain
  global-config:
    id-type: 2
    field-strategy: 1
    db-column-underline: false
    capital-mode: false
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    logic-not-delete-value: 0
    logic-delete-value: 1
    meta-object-handler: com.personal.common.mp.MpMetaObjectHandler
mybatis-plus:
    configuration:
      map-underscore-to-camel-case: false
      cache-enabled: false
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.personal.**.domain
    global-config:
      db-config:
        id-type: auto
        logic-delete-value: 0
        logic-not-delete-value: 1
        logic-delete-field: delFlag